/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rtp;

/**
 *
 * @author windows 8
 */
public class FirstScreen extends javax.swing.JFrame {

    /**
     * Creates new form FirstScreen
     */
    String type;
    int teacher_id;
    int id;

    public FirstScreen(String name, String type, int tid) {
        initComponents();
        tname.setText("Hola, " + name);
        this.type = type;
        id = tid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        time = new javax.swing.JLabel();
        tname = new javax.swing.JLabel();
        personal_info = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        internal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        screen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 105, 15));

        tname.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 13)); // NOI18N
        getContentPane().add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 24, 190, 20));

        personal_info.setText("Personal Information");
        personal_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personal_infoMouseClicked(evt);
            }
        });
        personal_info.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                personal_infoKeyPressed(evt);
            }
        });
        getContentPane().add(personal_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\files\\java\\RTP\\plan\\per_icon.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setAutoscrolls(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 50, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("G:\\files\\java\\RTP\\plan\\mse_icon.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 50, 50));

        internal.setText("Internal Marks");
        internal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                internalMouseClicked(evt);
            }
        });
        getContentPane().add(internal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("G:\\files\\java\\RTP\\plan\\result_icon.png")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 50, 40));

        jLabel6.setText("Results");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel7.setText("College Of Enginnering, Nagpur.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 350, 50));

        screen.setIcon(new javax.swing.ImageIcon("G:\\files\\java\\RTP\\style\\fp2.png")); // NOI18N
        getContentPane().add(screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 980, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personal_infoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personal_infoKeyPressed

    }//GEN-LAST:event_personal_infoKeyPressed

    private void internalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internalMouseClicked
        if (type.equals("Student")) {
            new InternalMarks(id).setVisible(true);
        } else if (type.equals("Teacher")) {
            new TeacherTableView(id).setVisible(true);
        }

    }//GEN-LAST:event_internalMouseClicked

    private void personal_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personal_infoMouseClicked
        new PersonalInfo(type,id).setVisible(true);
    }//GEN-LAST:event_personal_infoMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
         if (type.equals("Student")) {
            new result(id).setVisible(true);
        } else if (type.equals("Teacher")) {
            new ResultTableView(id).setVisible(true);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel internal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel personal_info;
    private javax.swing.JLabel screen;
    private javax.swing.JLabel time;
    private javax.swing.JLabel tname;
    // End of variables declaration//GEN-END:variables
}
