/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rtp;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author windows 8
 */
public class PersonalInfo extends javax.swing.JFrame {
    String df,type;int id;

    /**
     * Creates new form newuser
     */
    public PersonalInfo(String type,int id) {
        initComponents();
        this.id =id;
        this.type= type;
        try {
                
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rtp", "root", "");
            String sql2="";
            if(type.equals("Student")){
              sql2 = "select * from registration where id = '"+id+"'"; 
            }
            else if(type.equals("Teacher")){
              sql2 = "select * from teacher_data where id = '"+id+"'";}
            PreparedStatement pst = con.prepareStatement(sql2);
            ResultSet r = pst.executeQuery();
            while(r.next()){
            tid.setText(r.getString("id")); tid.setEnabled(false);
            tname.setText(r.getString("name")); tname.setEnabled(false);
            tmothername.setText(r.getString("mother_name")); tmothername.setEnabled(false);
            tcast.setText(r.getString("cast")); tcast.setEnabled(false);
            treligion.setSelectedItem(r.getString("religion")); treligion.setEnabled(false);
            tgender.setSelectedItem(r.getString("gender")); tgender.setEnabled(false);
            tcontact.setText(r.getString("contact")); tcontact.setEnabled(false);
            String d = r.getString("dob"); 
            java.util.Date a = new SimpleDateFormat("dd/MM/yyyy").parse(d);
            tdob.setDate(a); tdob.setEnabled(false);
            String f = r.getString("doa");
            java.util.Date b = new SimpleDateFormat("dd/MM/yyyy").parse(f);
            tdoa.setDate(b); tdoa.setEnabled(false);
            tadd.setText(r.getString("address")); tadd.setEnabled(false);
            tyear.setSelectedItem(r.getString("year")); tyear.setEnabled(false);
            tsem.setSelectedItem(r.getString("semester")); tsem.setEnabled(false);
            tbranch.setSelectedItem(r.getString("branch")); tbranch.setEnabled(false);
            tbg.setSelectedItem(r.getString("blood")); tbg.setEnabled(false);
            df = "G:\\files\\java\\RTP\\photos\\" + r.getString("photo"); 
            ImageIcon myImg = new ImageIcon(df);
            Image img = myImg.getImage();
            Image newImg = img.getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
            photo.setIcon(new ImageIcon(newImg));
            ttype.setSelectedItem(r.getString("type")); ttype.setEnabled(false);
            }
            
            
        } catch (Exception e) { e.printStackTrace();
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tdob = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        tdoa = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tadd = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        tyear = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tsem = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tbranch = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tgender = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tmothername = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tcontact = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tcast = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        treligion = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        tbg = new javax.swing.JComboBox<>();
        photo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ttype = new javax.swing.JComboBox<>();
        image = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Information Preview");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 250, 50));

        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 40, 20));
        getContentPane().add(tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 210, -1));

        jLabel4.setText("ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 20, -1));
        getContentPane().add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 110, -1));

        jLabel5.setText("DOB:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 20));

        tdob.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(tdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 120, 20));

        jLabel6.setText("Date of Admission:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, 20));

        tdoa.setDateFormatString("dd/MM/yyyy");
        getContentPane().add(tdoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 130, 20));

        jLabel7.setText("Address:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        tadd.setColumns(20);
        tadd.setRows(5);
        jScrollPane1.setViewportView(tadd);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 240, 60));

        jLabel8.setText("Year:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 30, -1));

        tyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "1", "2", "3", "4" }));
        getContentPane().add(tyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 120, -1));

        jLabel9.setText("Semester:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        tsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(tsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 120, -1));

        jLabel1.setText("Branch:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        tbranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "Computer Science & Engg.", "Mechanical Engg.", "Information Technology", "Civil Engg.", "CSE AI&ML", "Electrical Engg.", "Electromics Engg." }));
        getContentPane().add(tbranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 170, -1));

        jLabel10.setText("Gender: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        tgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "Male", "Female", "Others" }));
        getContentPane().add(tgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 90, 20));

        jLabel11.setText("Mother's Name: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        getContentPane().add(tmothername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 150, -1));

        jLabel12.setText(" Contact No.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));
        getContentPane().add(tcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 150, -1));

        jLabel13.setText("Cast : ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));
        getContentPane().add(tcast, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 100, -1));

        jLabel14.setText("Religion: ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        treligion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "Hindu", "Bodha", "Sikh", "Muslim", "Others.." }));
        getContentPane().add(treligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 100, -1));

        jLabel15.setText("Blood Group: ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, -1));

        tbg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", "rH other" }));
        getContentPane().add(tbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 90, -1));

        photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photo.setText("Photo");
        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        photo.setFocusable(false);
        photo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 114, 170, 160));

        jLabel17.setText("Type");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        ttype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher", "Management_staff" }));
        ttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttypeActionPerformed(evt);
            }
        });
        getContentPane().add(ttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 130, -1));

        image.setIcon(new javax.swing.ImageIcon("G:\\files\\java\\RTP\\style\\details.png")); // NOI18N
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 920, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PersonalInfo(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel photo;
    private javax.swing.JTextArea tadd;
    private javax.swing.JComboBox<String> tbg;
    private javax.swing.JComboBox<String> tbranch;
    private javax.swing.JTextField tcast;
    private javax.swing.JTextField tcontact;
    private com.toedter.calendar.JDateChooser tdoa;
    private com.toedter.calendar.JDateChooser tdob;
    private javax.swing.JComboBox<String> tgender;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tmothername;
    private javax.swing.JTextField tname;
    private javax.swing.JComboBox<String> treligion;
    private javax.swing.JComboBox<String> tsem;
    private javax.swing.JComboBox<String> ttype;
    private javax.swing.JComboBox<String> tyear;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
