/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rtp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author windows 8
 */
public class resultTeacher extends javax.swing.JFrame {
    int teacher_id,student_id;
    /**
     * Creates new form resultTeacher
     */
    public resultTeacher(int student_id,int id) {
        initComponents();
        teacher_id =id;
        treg.setText(String.valueOf(student_id));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        treg = new javax.swing.JTextField();
        tese = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tsem = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tsub = new javax.swing.JComboBox<>();
        bupdate = new javax.swing.JButton();
        tupload = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel2.setText("Result");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 160, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ESE Marks :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 80, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Reg no : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 60, 30));
        getContentPane().add(treg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 140, 20));
        getContentPane().add(tese, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 50, 20));

        jLabel5.setText("/40");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Select Sem :  ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        tsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        tsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsemActionPerformed(evt);
            }
        });
        getContentPane().add(tsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 50, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Select Subject: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        tsub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-" }));
        getContentPane().add(tsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 160, -1));

        bupdate.setText("Update");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });
        getContentPane().add(bupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        tupload.setText("Upload");
        tupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuploadActionPerformed(evt);
            }
        });
        getContentPane().add(tupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\files\\java\\RTP\\BG\\result.png")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsemActionPerformed
       if(tsem.getSelectedItem().equals("1")){
          tsub.addItem("M1");
          tsub.addItem("E chemistry");
          tsub.addItem("E Graphics");
          tsub.addItem("ELectrical E");
          tsub.addItem("Basic Electronics");
        }
        else if(tsem.getSelectedItem().equals("2")){
          tsub.addItem("M2");
          tsub.addItem("ITCP");
          tsub.addItem("E. Machanics");
          tsub.addItem("Communication Skills");
          tsub.addItem("E. Physics");
        }
        else if(tsem.getSelectedItem().equals("3")){
          tsub.addItem("M3");
          tsub.addItem("CAO");
          tsub.addItem("OOP");
          tsub.addItem("DS1");
        }
        else if(tsem.getSelectedItem().equals("4")){
          tsub.addItem("DMGT");
          tsub.addItem("OS");
          tsub.addItem("DS2");
          tsub.addItem("IDA");
          tsub.addItem("TOC");
        }
        else if(tsem.getSelectedItem().equals("5")){
          tsub.addItem("DBMS");
          tsub.addItem("DAA");
          tsub.addItem("PE1");
          tsub.addItem("OE1");
          tsub.addItem("OE2");
        }
        else if(tsem.getSelectedItem().equals("6")){
          tsub.addItem("CN");
          tsub.addItem("COMPILERS");
          tsub.addItem("SE");
          tsub.addItem("PE2");
          tsub.addItem("OE3");
          tsub.addItem("OE4");
          
        }
        else if(tsem.getSelectedItem().equals("7")){
          tsub.addItem("AI");
          tsub.addItem("CNS");
          tsub.addItem("PE3");
          tsub.addItem("PE4");
          tsub.addItem("PE5");
        }
    }//GEN-LAST:event_tsemActionPerformed

    private void tuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuploadActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/rtp", "root", "");
            String sql = "INSERT INTO ese(id,marks,sem,subject) VALUES ('"+treg.getText()+"','"+tese.getText()+"','"+tsem.getSelectedItem()+"','"+tsub.getSelectedItem()+"')";
            PreparedStatement pst = con.prepareStatement(sql);
            if(pst.executeUpdate()>0){
              JOptionPane.showMessageDialog(rootPane, "Data Updated SuccessFully");
            }
            else {
              JOptionPane.showMessageDialog(rootPane, "Data Updation Failed");
            }
            
        }
        catch (Exception e) {
            e.printStackTrace();
        
        }
    }//GEN-LAST:event_tuploadActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/rtp", "root", "");
            String sql = "UPDATE ese SET marks='"+tese.getText()+"',sem='"+tsem.getSelectedItem()+"',subject= '"+tsub.getSelectedItem()+"' WHERE id='"+treg.getText()+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            if(pst.executeUpdate()>0){
              JOptionPane.showMessageDialog(rootPane, "Data Updated SuccessFully");
            }
            else {
              JOptionPane.showMessageDialog(rootPane, "Data Updation Failed");
            }
        } catch (Exception e) { e.printStackTrace();
        }
    }//GEN-LAST:event_bupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new resultTeacher(student_id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tese;
    private javax.swing.JTextField treg;
    private javax.swing.JComboBox<String> tsem;
    private javax.swing.JComboBox<String> tsub;
    private javax.swing.JButton tupload;
    // End of variables declaration//GEN-END:variables
}
