/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rtp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author windows 8
 */
public class TeacherTableView extends javax.swing.JFrame {
        int teacher_id,student_id;
    /**
     * Creates new form InternalMarks
     */
    public TeacherTableView(int id) {
        initComponents();
        teacher_id =id;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tsem = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tsub = new javax.swing.JComboBox<>();
        label = new javax.swing.JLabel();
        tcc = new javax.swing.JLabel();
        tsubject = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        bview = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Select Semester:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 110, -1));

        tsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        tsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsemActionPerformed(evt);
            }
        });
        getContentPane().add(tsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 50, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Select Subject: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        tsub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-select-" }));
        getContentPane().add(tsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 190, -1));

        label.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 570, 30));

        tcc.setText("Course Code:");
        getContentPane().add(tcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 70, 20));

        tsubject.setText("Subject");
        getContentPane().add(tsubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 220, 20));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("* Contact Subject Teacher for any queries regarding marks..");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 300, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 560, 170));

        bview.setText("View");
        bview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bviewActionPerformed(evt);
            }
        });
        getContentPane().add(bview, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel3.setText("search by REG ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, -1));

        tid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tidKeyTyped(evt);
            }
        });
        getContentPane().add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 150, -1));

        photo.setIcon(new javax.swing.ImageIcon("G:\\files\\java\\RTP\\style\\mse.png")); // NOI18N
        getContentPane().add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 914, 582));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsemActionPerformed
       if(tsem.getSelectedItem().equals("1")){
          tsub.addItem("M1");
          tsub.addItem("E chemistry");
          tsub.addItem("E Graphics");
          tsub.addItem("ELectrical E");
          tsub.addItem("Basic Electronics");
        }
        else if(tsem.getSelectedItem().equals("2")){
          tsub.addItem("M2");
          tsub.addItem("ITCP");
          tsub.addItem("E. Machanics");
          tsub.addItem("Communication Skills");
          tsub.addItem("E. Physics");
        }
        else if(tsem.getSelectedItem().equals("3")){
          tsub.addItem("M3");
          tsub.addItem("CAO");
          tsub.addItem("OOP");
          tsub.addItem("DS1");
        }
        else if(tsem.getSelectedItem().equals("4")){
          tsub.addItem("DMGT");
          tsub.addItem("OS");
          tsub.addItem("DS2");
          tsub.addItem("IDA");
          tsub.addItem("TOC");
        }
        else if(tsem.getSelectedItem().equals("5")){
          tsub.addItem("DBMS");
          tsub.addItem("DAA");
          tsub.addItem("PE1");
          tsub.addItem("OE1");
          tsub.addItem("OE2");
        }
        else if(tsem.getSelectedItem().equals("6")){
          tsub.addItem("CN");
          tsub.addItem("COMPILERS");
          tsub.addItem("SE");
          tsub.addItem("PE2");
          tsub.addItem("OE3");
          tsub.addItem("OE4");
          
        }
        else if(tsem.getSelectedItem().equals("7")){
          tsub.addItem("AI");
          tsub.addItem("CNS");
          tsub.addItem("PE3");
          tsub.addItem("PE4");
          tsub.addItem("PE5");
        }
    }//GEN-LAST:event_tsemActionPerformed

    private void bviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bviewActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rtp", "root", "");
            String sql = "select id,name,semester,year from registration ";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
            
            

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bviewActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        TableModel model = table.getModel();
         int row =  table.getSelectedRow();
         student_id =(int)( model.getValueAt(row,0));
         new InternalMarksTeacher(student_id,teacher_id).setVisible(true);
         
         
         
    }//GEN-LAST:event_tableMouseClicked

    private void tidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tidKeyTyped
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/rtp", "root", "");
            String sql = "select * from marks where id like '%" + tid.getText() + "' ";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            

                table.setModel(DbUtils.resultSetToTableModel(rs));
            

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tidKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherTableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherTableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherTableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherTableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel photo;
    private javax.swing.JTable table;
    private javax.swing.JLabel tcc;
    private javax.swing.JTextField tid;
    private javax.swing.JComboBox<String> tsem;
    private javax.swing.JComboBox<String> tsub;
    private javax.swing.JLabel tsubject;
    // End of variables declaration//GEN-END:variables
}
